congrats_phrases = [
    "Congratulations! That's one more done, keep up the good work!",
    "Bu-dauh-dum, dum, dum, another one bites the dust! Great job!",
    "One step closer to finishing what you need to do, congratuations!",
    "You're doing so well! You should be proud of yourself :)"
    "I'm so proud of you, your motivation is paying off!",
    "Wow, you're working so hard! You'll have this done in no time!",
    "You're doing a great job! One step closer to being done!",
    "Fantastic job! I see you working hard, you're doing an amazing job!",
    "My, you'll have everything done in no time! Excellent work!",
    "It looks so much better, you did a great job!",
    "It doesn't matter how long it took as long as you're ok with it :) You did amazing!",
    "Doing it a little is better than not at all, great job for working on it!",
    "Take a second to look around, you've done so much already! Be proud!",
    "You're working so well, remember to drink something before you continue :)",
    "Jeez, did you hire someone to help you? This is a fantastic job!",
    "Remember to take a break if you need one, be easy with yourself <3",
    "Way to go superstar! -Glamrock Freddy",
    "Annnnnnd there's another done! Keep it up, you're doing so well!",
    "A++! I appreciate what you're doing, take a drink if you haven't in a while",
    "If the zombie apocalypse were to start tomorrow, I have every faith that you'd survive :)",
    "Great work on focusing, I see you doing your best! It doesn't matter what you could do yesterday as long as you're trying today",
    "I'm so proud of you for working through all this stuff!",
    "",
    "",
    ""
]